### ISSUE TITLE
Image-Style/ Render Bug 

### ISSUE THREAD

**Issue by trinityzhub** [mapgears/ol3-google-maps#124]
![111](https://cloud.githubusercontent.com/assets/20397671/18041370/a31bc2b2-6dd5-11e6-8b87-e938a04b36f7.png)

if style contains image like  
                                 new ol.style.Style({
                                                      image: new ol.style.Icon(/*\* @type {olx.style.IconOptions} */ ({
                                                        anchor: [0.5, 46],
                                                        anchorXUnits: 'fraction',
                                                        anchorYUnits: 'pixels',
                                                        opacity: 0.75,
                                                        src: pick
                                                      })),
                                                      text: new ol.style.Text({
                                                      font: '14px Calibri,sans-serif',
                                                      fill: new ol.style.Fill({ color: 'black' , width: 2}),
                                                      stroke: new ol.style.Stroke({
                                                        color: 'green', width: 4
                                                      }),
                                                      text: labltxt
                                                    })
                                                });
while using vectorContext.drawFeature(feature,style) in ol3gm.

it will end up with bug.

 TypeError: b is Null.

---

I can fix this bug by adding the style only after the map render.
But It is Impossible
Because
**# MAP.RENDER();
MAP.UPDATESIZE();**
are NOT WORKING in OL3GM

So I called my function after 1000ms. It worked, But timer is not satisfactory.

So please suggest any other solution for render / style problem

**Comment by adube** [comment]
Would you please try with the 0.10.2 version?  We fixed something that seems like that.

**Comment by trinityzhub** [comment]
I tried in 0.10 But the map.render() is not Rendering and Style bug still in it (TypeError is only Changed from "c" to "b" ).

**Comment by adube** [comment]
Have you tried with 0.10.**2**?  Also, if you could create a JSFiddle example out of this that demonstrates the issue that would help us fixing it.  Thanks!

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
